version: "3.3"

services:
    app:
        image: vadimmakerov/orderservice:master
        container_name: orderservice-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: percona
        container_name: go_app_db
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - 3306:3306
        healthcheck:
            test: mysql -h127.0.0.1 -uroot -p1234 -e 'SELECT 1'
            interval: 20s
            timeout: 1s